### ISSUE TITLE
Difference to the other packages?

### ISSUE THREAD

**Issue by bernhardh** [Naoray/nova-json#1]
Not sure, if this is a "dumb" question - what is the difference or benefit to the other nova json packages?

- https://novapackages.com/packages/nsavinov/nova-json-schema-field
- https://novapackages.com/packages/ibrahem-kamal/json-field
- https://novapackages.com/packages/digital-creative/nova-json-wrapper
- https://novapackages.com/packages/armincms/json

**Comment by Naoray** [comment]
Hi @bernhardh,

>https://novapackages.com/packages/nsavinov/nova-json-schema-field
https://novapackages.com/packages/ibrahem-kamal/json-field

Those two packages don't allow you to use standard Nova Fields. They require you to work with another format.

> https://novapackages.com/packages/digital-creative/nova-json-wrapper
https://novapackages.com/packages/armincms/json

They look interesting, especially the second one. But I don't like packages that are not maintained (issues are ignored) and are without tests.

At this point I'd say it comes down to your personal preference. The last two and mine are pretty similar except that mine currently doesn't allow nested data, which will be implemented soon.

**Comment by bernhardh** [comment]
Thanks for feedback! I am currently using armincms/json atm, but always looking for better alternatives.

**Comment by Naoray** [comment]
Thanks for asking!

**Comment by Naoray** [comment]
@bernhardh you now can also use nested `JSON` structures with this package.

After using my package and comparing it to `armincms/json` I also found out that my package does support using custom casts e.g. with spatie's [data transfer object](https://github.com/spatie/data-transfer-object). `armincms/json` does not seem to support custom casts.
