### ISSUE TITLE
Package not working with Nova ^4.0 and Laravel 9

### ISSUE THREAD

**Issue by WetDry** [Naoray/nova-json#12]
Hello, i want report an issue dicovered when i tried to install this package inside my Nova ^4.0 with Laravel 9 as Framework version.

Error: `  Problem 1
    - Root composer.json requires naoray/nova-json ^2.0 -> satisfiable by naoray/nova-json[v2.0.0].
    - naoray/nova-json v2.0.0 requires laravel/nova ^3.0 -> found laravel/nova[dev-master, v3.0.0, ..., 3.x-dev (alias of dev-master)] but it conflicts with your root composer.json require (~4.0).

Use the option --with-all-dependencies (-W) to allow upgrades, downgrades and removals for packages currently locked to specific versions.`

Any suggest? Thank you!

**Comment by e1real** [comment]
Hi, any news?

**Comment by gisostallenberg** [comment]
@chrisvasey That is not a fork and it works very different.

See https://github.com/Naoray/nova-json/pull/14 for Nova 4 compatibility.
Until it is merged you could add a compatible version by running:
```bash
composer config repositories.nova-json git https://github.com/gisostallenberg/nova-json
composer require naoray/nova-json:'dev-nova-4 || ^2.1'
```
