### ISSUE TITLE
Wrapping a JSON field within a Panel causes the panel to be hidden

### ISSUE THREAD

**Issue by Naoray** [Naoray/nova-json#2]
```php
Text::make('Phone')
                ->rules('required', 'string'),

Panel::make('Brand Settings', [
                JSON::make('brand_settings', [
                    Image::make('Logo')->disk('public'),
                    Color::make('Primary Color')->swatches(),
                    Color::make('Secondary Color')->swatches(),
                ]),
            ]),
```

![image](https://user-images.githubusercontent.com/10154100/104184920-85744200-5414-11eb-92ab-e3a4232ccad9.png)

**Comment by elijahworkz** [comment]
There are a couple of way to solve this without changing the code

1. don't wrap JSON::make() in [] so it would look like this:
`Panel::make('Brand Settings', 
                JSON::make('brand_settings', [
                    Image::make('Logo')->disk('public'),
                    Color::make('Primary Color')->swatches(),
                    Color::make('Secondary Color')->swatches(),
                ]),
            ),`
2. if you need other fields inside the Panel you can use splat operator like this:
`Panel::make('Brand Settings', [
Text::make('Field'),
                ...JSON::make('brand_settings', [
                    Image::make('Logo')->disk('public'),
                    Color::make('Primary Color')->swatches(),
                    Color::make('Secondary Color')->swatches(),
                ]),
            ]),`

**Comment by Naoray** [comment]
@elijahworkz I tested both approaches and none of them worked. First approach did throw errors related to the fact that the `JSON` class does not inherit from `Field`. Second approach is not possible because you can't deconstruct associative arrays with `...`

**Comment by elijahworkz** [comment]
@Naoray you're right. I forgot to add that you need to get the property 'data' from the top JSON field.

Like this:
1. don't wrap JSON::make() in [] so it would look like this:
```php
Panel::make('Brand Settings', 
                JSON::make('brand_settings', [
                    Image::make('Logo')->disk('public'),
                    Color::make('Primary Color')->swatches(),
                    Color::make('Secondary Color')->swatches(),
                ])->data,
            ),
```
2. if you need other fields inside the Panel you can use splat operator like this:
```php
Panel::make('Brand Settings', [
                Text::make('Field'),
                ...JSON::make('brand_settings', [
                    Image::make('Logo')->disk('public'),
                    Color::make('Primary Color')->swatches(),
                    Color::make('Secondary Color')->swatches(),
                ])->data,
            ]),
```

**Comment by Naoray** [comment]
@elijahworkz thanks. That works :handshake:
