### ISSUE TITLE
Not compatible with laravel <8

### ISSUE THREAD

**Issue by bernhardh** [Naoray/nova-json#3]
Not sure, but I think you package isn't compatible with laravel <8?

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires naoray/nova-json ^1.1 -> satisfiable by naoray/nova-json[v1.1.0].
    - naoray/nova-json v1.1.0 requires illuminate/http ^8.0 -> found illuminate/http[v8.0.0, ..., 8.x-dev] but it conflicts with another require.

```

**Comment by Naoray** [comment]
Yes, I did create it when Laravel 8 was out and therefore didn't bother to make it compatible for versions < v8. I think it could be possible to change the composer requirements without the need for any other change. Feel free to submit a PR
